### ISSUE TITLE
permission_unknown error

### ISSUE THREAD

**Issue by mh-github** [hexgnu/linkedin#134]
Hi,

I followed the steps given in  authenticate.rb (https://github.com/pengwynn/linkedin/blob/master/examples/authenticate.rb)

At the line client.authorize_from_request(rtoken, rsecret, pin) which for me is
client.authorize_from_request(rtoken, rsecret, 13404)

I am getting the following error:

C:/Ruby193/lib/ruby/gems/1.9.1/gems/oauth-0.4.6/lib/oauth/consumer.rb:178:in `re
quest': permission_unknown (OAuth::Problem)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/oauth-0.4.6/lib/oauth/consumer.
rb:194:in`token_request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/oauth-0.4.6/lib/oauth/tokens/re
quest_token.rb:18:in `get_access_token'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/linkedin-0.3.7/lib/linked_in/he
lpers/authorization.rb:29:in`authorize_from_request'

How do I resolve this?

Thanks
Mahboob

**Comment by tamersalama** [comment]
For reference:

1- Generate API Key (consumer API) and consumer secret from the website.

2- Generate `request_token` and URL for authorization
```
client = LinkedIn::Client.new(<consumer_api>, <consumer_secret>)
request_token = client.request_token({}, :scope => "r_fullprofile")
rtoken = request_token.token
rsecret = request_token.secret
request_token = client.request_token({}, :scope => "r_fullprofile")
puts rtoken
puts rsecret
puts request_token.authorize_url
#=> 54--5738......484
#=> 66-87237.....233
#=> https://api.linkedin.com/uas/oauth/authorize?oauth_token=<generated_token>
```

*__Do not call the above code again or it will generate a new token. Record the rtoken and rsecret values__*

3- Visit the generated URL to grant permission

4- Fetch the access keys
```
client = LinkedIn::Client.new(<consumer_api>, <consumer_secret>)
puts client.authorize_from_request(rtoken, rsecret, pin)
#=> ["176658....", "167857..."]
```
*__Record the access keys__*

5- Use the access keys from now on
```
client = LinkedIn::Client.new(<consumer_api>, <consumer_secret>)
client.authorize_from_access("176658....", "167857...")

client.profile
#...
```
