### ISSUE TITLE
Moving to OAuth2

### ISSUE THREAD

**Issue by ekampp** [hexgnu/linkedin#178]
This is a discussion, to roadmap the best solution for moving to OAuth2. 

I have found the [linkedin-oauth2 gem](https://rubygems.org/gems/linkedin-oauth2), which has already moved to oauth2. Perhaps, we should take a look at reverse engineering that to implement the changes that fits this project?

**Comment by ArbolIntl** [comment]
https://github.com/emorikawa/linkedin-oauth2 is where you want to go if you are using oauth2.

**Comment by ekampp** [comment]
Yep. This is dead.
