### ISSUE TITLE
token_secret is not passed

### ISSUE THREAD

**Issue by LeKristapino** [hexgnu/linkedin#255]
I tried looking at the callback hash of omniauth and I can't seem to find token_secret which is needed for this gem.

It only returns token and expiry date. Nothing about the secret. 

Any suggestions?

**Comment by hexgnu** [comment]
Are you using omniauth-linkedin or omniauth-linkedin2?

**Comment by LeKristapino** [comment]
Fixed it. That was my problem. I was using omniauth-linkedin-oauth2 , but used a linkedin wrapper for Oauth 1.0a. When 'linkedin-oauth2' gem fixed the problem
