### ISSUE TITLE
(400): 'submitted-url' and 'media-key' can not be both empty

### ISSUE THREAD

**Issue by jbolles5** [hexgnu/linkedin#258]
I have recently started getting this error when using the add_company_share method. I am passing 'submitted-url' and 'submitted-image-url' into the content section, as indicated by the documentation here: https://developer.linkedin.com/docs/company-pages#company_share

For the life of me I can't find media-key anywhere in the documentation. What am I missing here? Any help would be appreciated.

Actual post code:
```
result = client.add_company_share(published_post.channel_account.channel_id, { comment: scheduled_post.post_text, content: { 'submitted-image-url' => scheduled_post.post_image.url,  'submitted-url' => scheduled_post.link  } })
```

**Comment by hexgnu** [comment]
Hrm... weird I haven't heard of media-key either.

Have you tried setting media-key to blank?

**Comment by jbolles5** [comment]
I just set media-key to blank and the post went through. Odd. Closing this issue, thanks for the help.

**Comment by sonalmahajan01** [comment]
I just want to add content by myself and share a image with it and there is no url of any content. So i dont want to send submitted-url. When i tried that, it does not get posted and give the above error :+1: 
"'submitted-url' and 'media-key' can not be both empty". So i changed it to below but still the error is coming
{"visibility":{"code":"anyone"},"comment":"testing","content":{"media-key":"","submitted-image-url":"http:\/\/brsresults.files.wordpress.com\/2015\/06\/dodge-durango-ron-burgundy-asleep-at-the-wheel.jpg"}}

**Comment by danielbonnell** [comment]
I just started encountering this problem in my app. I've set `'media-key` => ''` in my options hash but I still get the error whenever I'm not submitting a `submitted-url`, even if I just set `'submitted-url' => ''` in my hash. This is strange because LinkedIn doesn't require you to include a link when posting a share through their native UI.

**Comment by jbolles5** [comment]
As best I can tell, you must include Submitted URL, Image URL, and media key in order to post anything that is not just a plain text post. 




Justin Bolles connectthink 

O | 317.682.0282 

C | 317.201.4516 

www.connectthink.com

**Comment by danielbonnell** [comment]
So do I need to be submitting shares without a `media-url` as a `comment`?

**Comment by sagar2agrawal** [comment]
yes, that will work
