### ISSUE TITLE
problems with the access token

### ISSUE THREAD

**Issue by KevinMartins367** [hexgnu/linkedin#271]
I do not know if I'm doing something wrong, but it does not hurt to know ...
I am authenticating by the javascript SDK in my project and saving the tokens in the database to try to update the token by this gem. But I'm getting it as if it were an invalid token 
![](https://raw.githubusercontent.com/KevinMartins367/KevinMartins367.github.io/master/images/token%20linkedin2.png)
```
        @client = LinkedIn::Client.new
        @client.authorize_from_access(user[oauth_token], user[anonymous_token])
        test = @client.profile
```

`LinkedIn :: Errors :: UnauthorizedError ((401): [unauthorized].) The token used in the OAuth request is not valid consumerKey: 'MY_KEY') :`
Or am I running the wrong way? (yes, I'm running this before the token expires)

**Comment by hexgnu** [comment]
Hey @KevinMartins367.

I'm not actually sure, I haven't ever tried authenticating through the javascript SDK. I'm not actually sure it will work or not. If you figure it out let me know.

**Comment by KevinMartins367** [comment]
Hello, I do not know why, but the javascript lib I used did not return a valid token for this gem, but I was able to perform authentication without problems using gem-only. @hexgnu
