### ISSUE TITLE
oauth token rejected issues

### ISSUE THREAD

**Issue by mguterl** [hexgnu/linkedin#49]
We implemented some features using linkedin 0.2.2 and everything works fine most of the time.  Occasionally we are receiving OAuth::Problem token_rejected errors during the authorize_from_request method.

I have looked at [Tips on Debugging OAuth Problems](http://developer.linkedin.com/message/1996#1996) on LinkedIn's developer docs, but I don't think any of those are relevant.

I'm fairly new to the whole OAuth dance, has anyone else experienced anything similar?

**Comment by javapriyan** [comment]
We are facing the same issue. Is something broken again ?

**Comment by hexgnu** [comment]
@javapriyan any more information would be useful. I have no clue out of context :smile:s

**Comment by javapriyan** [comment]
Often I get this 'oauth_problem=token_rejected' issue. Here is the stack trace.http://paste.opensuse.org/57675457

**Comment by hexgnu** [comment]
@javapriyan Are you sure you're asking the right repo? This repo is the ruby linkedin library.

Really it seems like you'd have better luck asking the linkedin developer forum or scribe about the specific issue. Also without seeing the source code I have no idea what the issue could be.

Thanks :smile:

**Comment by javapriyan** [comment]
@hexgnu Oh my bad. Wrong room :) Thanks.
